version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: codingjenner/pruru-back
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: on-failure
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_DB: "mysql-container"
      DB_HOST_NAME: "mysql"
      DB_PORT: "3306"
      MYSQL_ROOT_USER: "${DB_USER}"
      MYSQL_ROOT_PASSWORD: "${DOCKERMYSQL_PASSWORD}"
    volumes:
      - .:/src
      - /src/node_modules
    networks:
      - refrigeratornetwork
  mysql:
    image: mysql:8
    container_name: mysql-container
    # platform: linux/arm64
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
      - refrigerator-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DOCKERMYSQL_PASSWORD}"
      MYSQL_ROOT_USER: "${DB_USER}"
      MYSQL_DATABASE: "mysql-container"
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
    env_file:
      - .env
    restart: always
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --bind-address=0.0.0.0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - refrigeratornetwork
  pruru-front:
    build: ../pruru_front
    image: codingjenner/pruru-front
    ports:
      - "80:80"
    networks:
      - refrigeratornetwork
    env_file:
      - .env
volumes:
  refrigerator-mysql-data:
networks:
  refrigeratornetwork:
    driver: bridge
