version: "3.7"
services:
  app:
    image: node:20-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 5001:5001
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: mysql-container
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DOCKERMYSQL_PASSWORD}
    volumes:
      - refrigerator-mysql-data:/usr/src/app
    networks:
      - refrigeratornetwork
  mysql:
    image: mysql:8
    platform: linux/arm64
    ports:
      - 3306:3306
    volumes:
      - refrigerator-mysql-data:/usr/src/mysql
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DOCKERMYSQL_PASSWORD}
      MYSQL_DATABASE: mysql-container
    networks:
      - refrigeratornetwork
volumes:
  refrigerator-mysql-data:
networks:
  refrigeratornetwork:
    external: true
