version: "3.7"

services:
  app:
    image: node:20-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 5001:5001
    working_dir: /app
    volumes:
      - ./:/app

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: my-refrigerator

volumes:
  todo-mysql-data:
